name: ipyautoui-docs
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
# -
# jg notes
# - 
# - needs everything that ipyautoui needs + everything for docs
# - in future when packaged could make ipyautoui a dependency
channels:
  - defaults
  - conda-forge
#  - http://10.10.30.125:8000
dependencies:
  - python>=3.7,<3.10
  - numpy
  - pandas
  - matplotlib
  - jupyterlab>=3.0.14
  - xeus-python
  - ipywidgets
  - ipysheet>=0.5.0
  - ipyfilechooser
  - ipydatagrid
#  - ipyrun>=v0.1.9
  - voila>=0.2.11
  - plotly
  - halo
  - jupytext
  - markdown
  - nodejs
  - altair
  - pydantic
  - dacite
  - xmltodict
  - pyyaml
  - pillow
#  - click
  - openpyxl
  - black
  - nb_black
  - immutables
  - wcmatch
  - jupyter-book # for docs
  - sphinx # for docs
  - sphinx-book-theme # for docs
  - sphinx-autoapi
  - autodoc-pydantic # for docs
  - nbsphinx-link
  - pytest
  - pip
  - pip:
    - traitlets-paths
#  - xlsxwriter 
#  - xlsxtemplater 
#  - mf_file_utilities 
#  - mfom
